name: commande2
on:
  push:
    branches:
      - develop
jobs:
  Mon-Premier-Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cjheckout@v2
      - name: list file directory
        run: ls
      - name: change permission install.sh
        run: chmode 711 ./.github/scripts/install.sh
      - name: listes des fichiers
      - run: ./.github/scripts/install.sh
        shell: bash
